### ISSUE TITLE
Important: MenuItems 

### ISSUE THREAD

**Issue by blerude** [MJeekhof/expressoProject#3]
https://github.com/MJeekhof/expressoProject/blob/master/api/menus.js#L130-L232

It appears that your menu item routes are actually dealing with menus themselves. For example, your values in the post function are just title and name, instead of the actual menu items values of price, inventory, etc. Look into this again.

**Comment by MJeekhof** [comment]
Overlooked this before resubmitting, working on it now!

**Comment by MJeekhof** [comment]
Added db values.
